# Generated by Django 3.1.3 on 2020-11-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_nome', models.CharField(help_text='Digite seu nome e sobrenome', max_length=100, verbose_name='Qual é o seu nome?')),
                ('vend_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nome', models.CharField(help_text='Digite o nome do produto', max_length=100, verbose_name='Qual é o nome do produto?')),
                ('prod_descricao', models.TextField(max_length=100)),
                ('prod_preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prod_codigo', models.IntegerField()),
                ('prod_qtd', models.IntegerField()),
                ('prod_inativo', models.BooleanField(default=False)),
                ('vend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lu_marketplace.vendedor')),
            ],
        ),
    ]
