# Generated by Django 3.1.3 on 2020-11-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lu_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='prod_codigo',
            field=models.IntegerField(verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_descricao',
            field=models.TextField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_qtd',
            field=models.IntegerField(verbose_name='Qauntidade'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vend_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vend_nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
