# Generated by Django 3.1.3 on 2020-11-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lu_marketplace', '0002_auto_20201118_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='prod_qtd',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
