# Generated by Django 3.1.3 on 2020-11-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lu_marketplace', '0004_auto_20201118_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lu_marketplace.vendedor', verbose_name='Vendedor'),
        ),
    ]
