# Generated by Django 3.1.3 on 2020-11-19 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lu_marketplace', '0005_auto_20201118_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_preco',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
