# Generated by Django 3.1.3 on 2020-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lu_marketplace', '0006_auto_20201119_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='prod_descricao',
            field=models.TextField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_nome',
            field=models.CharField(max_length=25, verbose_name='Nome'),
        ),
    ]
